name: Javadoc GH Pages
on:
  push:
    tags:
      - '*'
permissions:
  pages: write
  id-token: write
jobs:
  build:
    name: Javadoc Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build javadoc
        run: ./gradlew --no-daemon lib:javadoc
      - name: Upload javadocs
        uses: actions/upload-pages-artifact@v3
        with:
          path: lib/build/docs/javadoc
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy Javadoc
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
