name: Pull Request CI
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-latest ]
    steps:
      - name: Project checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build
        run: ./gradlew --no-daemon assemble
      - name: Test
        run: ./gradlew --no-daemon check
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.java }}
          path: '**/build/test-results/test/TEST-*.xml'

